# Cargar las librerías necesarias
library(tidyverse)

##
## Combining CSV from scratch downloader
##

# Cargar los archivos CSV
multi_titles <- read_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/multi/multi_sb3_titles.csv")
nomulti_titles <- read_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/no_multi/nomulti_sb3_titles.csv")

# Asegurarse de que los nombres de las columnas son consistentes
# Asumiendo que los archivos tienen columnas llamadas 'filename' y 'title'
# Si no es así, ajusta los nombres según corresponda
multi_titles <- multi_titles %>% select("Project ID", Title) %>% rename(filename="Project ID")
nomulti_titles <- nomulti_titles %>% select(filename, project_title) %>% rename(Title=project_title)

# Combinar los datasets
combined_titles <- bind_rows(multi_titles, nomulti_titles) %>% arrange(filename)

# Guardar el dataset combinado en un nuevo archivo CSV
write_csv(combined_titles, "C:/propios/Doc_sin_respaldo_nube/down_sb3/sb3_titles.csv")

combined_titles |> select(filename) |> write_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/sb3_litter.csv")

##
## Consolidating the Litterbox and DrScratch results.
##


litter_results <- read_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/litter_results_all.csv")
drscratch_results <- read_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/CT_results_nuevo.csv")

drscratch_results <- drscratch_results %>%
  mutate(project = str_remove(project, "\\.sb3$")) |> 
  mutate(project = as.double(project)) |>
  distinct(project, .keep_all = TRUE) # remove duplicates by the extraction process

litter_results <- litter_results %>%
  distinct(project, .keep_all = TRUE) # remove duplicates generated by the extraction process

dataset_unido <- litter_results %>%
  inner_join(drscratch_results, by = "project")

glimpse(dataset_unido)

dataset_unido |> write_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/X_TT_add.csv")

##
## Combine the former dataset with the new one that has just been created.
##

X_TT <- read_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/X_TT.csv")

# Obtener nombres de columnas
cols_XTT <- names(X_TT)
cols_du  <- names(dataset_unido)

# Intersección (columnas comunes)
(cols_comunes <- intersect(cols_XTT, cols_du))
setdiff(cols_XTT, cols_du)   # columnas solo en X_TT
setdiff(cols_du, cols_XTT)   # columnas solo en dataset_unido

X_TT <- X_TT %>%
  rename(
    project            = filename,
    duplicateScripts   = duplicateScript,
    babia_num_sprites  = total_blocks,
    backdropNaming     = spriteNaming
  )

dataset_unido_filtrado <- dataset_unido %>% 
  select(all_of(cols_comunes))

nuevas_obs <- dataset_unido_filtrado %>%
  anti_join(X_TT, by = "project")

X_TT_actualizado <- bind_rows(X_TT, nuevas_obs)

#########
# Falta añadir los metadatos ausentes
#########

# Buscar duplicados
X_TT_actualizado %>% filter(duplicated(.) | duplicated(., fromLast = TRUE))
X_TT_actualizado |>
  group_by_all() |>
  filter(n()>1) |>
  ungroup()

X_TT_actualizado <- X_TT_actualizado |> distinct()
X_TT_actualizado[!duplicated(X_TT_actualizado), ]

#Cargar archivos con metadatas adicionales a añadir
dataset_unido_meta <- read_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/CT_results_meta_nuevo.csv")
X_titles <- read_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/X_TT_titles.csv")

# Añadir a consolidado los nombres legacy
X_TT_actualizado <- X_TT_actualizado %>%
  left_join(
    X_titles %>% 
      rename(`Project title` = project_title),
    by = c("project" = "filename")
  )

X_TT_actualizado <- X_TT_actualizado %>%
  rows_update(
    dataset_unido_meta %>%
      rename(project = project_id) %>%
      select(project, `Project title`, Author, `Creation date`, 
             `Modified date`, `Remix parent id`, `Remix root id`),
    by = "project", unmatched = "ignore"
  )

X_TT_actualizado %>%
  filter(is.na(Author) | Author == "") %>%
  summarise(n = n())

# Ver registros con error en el nombre
X_TT_actualizado %>%
  filter(str_detect(`Project title`, "ERROR")) |> select(project,`Project title`)

#Borrar las observaciones con ERROR por projecto no encontrado
X_TT_actualizado <- X_TT_actualizado %>%
  filter(!str_detect(`Project title`, "ERROR"))

X_TT_actualizado %>%
  filter(is.na(`Project title`) | `Project title` == "") %>%
  summarise(n = n())

# Salvar consolidado
X_TT_actualizado |> write_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/X_TT_RR.csv")

# Cargar consolidado
X_TT_actualizado <- read_csv("C:/propios/Doc_sin_respaldo_nube/down_sb3/X_TT_RR.csv"
